### ISSUE TITLE
peek() is actually pop(); missing peek(); perhaps tpop()?

### ISSUE THREAD

**Issue by MikeFair** [solzimer/fileq#1]
Hi there,

I was looking around for a simple file backed FIFO message queue and found this library.
"peek" usually allows you to look at the head item on the queue without removing it.
"pop" usually is for removing an item from the queue.

I'm actually looking for the "peek" feature where I can process the head item on the queue first without removing it; and then after confirming it has successfully processed; remove it.

-----
One interesting and seemingly useful approach I saw on 'file-queue' was a "Transactional Pop".
The way it worked is you executed "tpop" and were given a "commit" and "rollback" callback functions.
You'd process the message, then call the appropriate callback when it was sorted out what to do.

A feature that would be really nice is a queue flag to indicate that a transaction is currently in progress.  I was iterating over several queues in a loop and found that I needed to introduce a queue_lock to prevent from processing multiple items from the queue simultaneously.

Hope that's useful!

Thanks for the library!

**Comment by solzimer** [comment]
Hi @MikeFair ,

Thanks for the comments. Some appreciations:

fileq is not a FIFO, but a LIFO (Last in, first out). Tipically, "push" adds an item to the head, and "pop" removes it from the head, in a FIFO manner (or javascript arrays push and pop methods). For a LIFO, it's true that "peek" allows you to see the item without removing it. It should have been more like a "peek" and "poll" methods (Like Java Queue interface https://docs.oracle.com/javase/7/docs/api/java/util/Queue.html).

That being said, this feature looks interesting, so i'll try to implement it without breaking the current API.

Thanks for the feedback!

**Comment by solzimer** [comment]
Done!

The new API and docs are available on https://github.com/solzimer/fileq
